package contract

import "github.com/maryzam/ai-crew-localdev/internal/interception"

func InterceptionProfile() interception.Profile {
	return interception.Profile{
		Provider: "langfuse",
		ScrubEnv: []string{
			"AI_AGENT_LANGFUSE_PUBLIC_KEY",
			"AI_AGENT_LANGFUSE_SECRET_KEY",
			"LANGFUSE_PUBLIC_KEY",
			"LANGFUSE_SECRET_KEY",
			"AI_AGENT_LANGFUSE_HOST",
			"LANGFUSE_HOST",
			"AI_AGENT_OTLP_HEADERS",
			"AI_AGENT_OTLP_TRACES_ENDPOINT",
			"AI_AGENT_OBSERVABILITY_RESOURCE",
			"OTEL_EXPORTER_OTLP_HEADERS",
			"OTEL_EXPORTER_OTLP_LOGS_HEADERS",
			"OTEL_EXPORTER_OTLP_TRACES_HEADERS",
			"OTEL_EXPORTER_OTLP_LOGS_ENDPOINT",
			"OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
			"OTEL_EXPORTER_OTLP_ENDPOINT",
			"OTEL_EXPORTER_OTLP_PROTOCOL",
			"OTEL_EXPORTER_OTLP_LOGS_PROTOCOL",
			"OTEL_EXPORTER_OTLP_TRACES_PROTOCOL",
			"OTEL_LOGS_EXPORTER",
			"OTEL_TRACES_EXPORTER",
			"OTEL_METRICS_EXPORTER",
			"OTEL_RESOURCE_ATTRIBUTES",
			"OTEL_LOGS_EXPORT_INTERVAL",
			"OTEL_TRACES_EXPORT_INTERVAL",
			"OTEL_METRICS_INCLUDE_ACCOUNT_UUID",
			"OTEL_LOG_USER_PROMPTS",
			"OTEL_LOG_TOOL_DETAILS",
			"OTEL_LOG_TOOL_CONTENT",
			"OTEL_LOG_RAW_API_BODIES",
			"CLAUDE_CODE_ENABLE_TELEMETRY",
			"CLAUDE_CODE_ENHANCED_TELEMETRY_BETA",
		},
	}
}
