package inlinecomments

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf8"
)

func TestCheckFileReportsOnlyAddedFunctionBodyComments(t *testing.T) {
	t.Parallel()

	path := writeGoFile(t, `package sample

// Package-level comments are allowed.
func existing() {
	// existing body comment
	println("existing")
}

func changed() {
	// newly added body comment
	println("changed")
}
`)

	findings, err := CheckFile(path, lineSet(10))
	if err != nil {
		t.Fatalf("CheckFile() error = %v", err)
	}
	if len(findings) != 1 {
		t.Fatalf("len(findings) = %d, want 1: %#v", len(findings), findings)
	}
	if findings[0].Line != 10 {
		t.Fatalf("finding line = %d, want 10", findings[0].Line)
	}
}

func TestCheckFileIgnoresGeneratedFilesAndDirectives(t *testing.T) {
	t.Parallel()

	path := writeGoFile(t, `// Code generated by test; DO NOT EDIT.
package sample

func generated() {
	// generated body comment
	println("generated")
}
`)

	findings, err := CheckFile(path, lineSet(4))
	if err != nil {
		t.Fatalf("CheckFile() error = %v", err)
	}
	if len(findings) != 0 {
		t.Fatalf("len(findings) = %d, want 0: %#v", len(findings), findings)
	}
}

func TestCheckFileIgnoresAllowedInlineDirectives(t *testing.T) {
	t.Parallel()

	path := writeGoFile(t, `package sample

func allowed() {
	//nolint:gocritic
	println("allowed")
}
`)

	findings, err := CheckFile(path, lineSet(4))
	if err != nil {
		t.Fatalf("CheckFile() error = %v", err)
	}
	if len(findings) != 0 {
		t.Fatalf("len(findings) = %d, want 0: %#v", len(findings), findings)
	}
}

func TestCheckSourceUsesProvidedContent(t *testing.T) {
	t.Parallel()

	source := []byte(`package sample

func changed() {
	// newly added body comment
	println("changed")
}
`)

	findings, err := CheckSource("sample.go", source, lineSet(4))
	if err != nil {
		t.Fatalf("CheckSource() error = %v", err)
	}
	if len(findings) != 1 {
		t.Fatalf("len(findings) = %d, want 1: %#v", len(findings), findings)
	}
}

func TestFirstLineTruncatesByRunes(t *testing.T) {
	t.Parallel()

	got := firstLine(strings.Repeat("界", 101))
	if !strings.HasSuffix(got, "...") {
		t.Fatalf("firstLine() = %q, want ellipsis suffix", got)
	}
	if !utf8.ValidString(got) {
		t.Fatalf("firstLine() returned invalid UTF-8: %q", got)
	}
}

func writeGoFile(t *testing.T, content string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "sample.go")
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write Go file: %v", err)
	}
	return path
}

func lineSet(lines ...int) map[int]struct{} {
	set := make(map[int]struct{}, len(lines))
	for _, line := range lines {
		set[line] = struct{}{}
	}
	return set
}
